spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: info

jwt:
  access-token:
    key: VlwEyVBsYt9V7zq57TejMnVUyZblYcfPQye08f7MgAA9XkHa
    expiration-time: 10
  refresh-token:
    key: VlwEyVBsYt9V7zq57TejMnVUyZblYcfPQye08f7MgAA9XkHa
    expiration-time: 60