name: Build and Deploy to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: ./gradlew test

      - name: Configure AWS credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        if: success()
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        if: success()
        run: |
          # Private ECR
          # IMAGE=${{ steps.login-ecr.outputs.registry }}/spring-webmvc-java:$(git rev-parse --short HEAD)

          # Public ECR
          IMAGE=public.ecr.aws/g0h3t1b1/spring-webmvc-java:$(git rev-parse --short HEAD)
               
          docker build -t $IMAGE .
          docker push $IMAGE
